<?php
/** Basics,
 * Please DO NOT EDIT this file. If you need any configuration set up or constants applied
 * please use RaccoonWP/configuration directory
 */

/* Load composer autoloader */
require_once(dirname(__DIR__) . '/vendor/autoload.php');

// Initializing new instance of RaccoonApp which does all of WP configuration init in similar way wp-config did
$app = new \RaccoonWP\RaccoonApp();
$app->initialize();

//Set up MySQL table prefix for that installation
$table_prefix = getenv('DB_PREFIX') ?: 'wp_';

//Include WordPress
require_once(ABSPATH . 'wp-settings.php');